### ISSUE TITLE
General TODO

### ISSUE THREAD

**Issue by yoavram** [yoavram/markx#16]
This is an issue for feature features
- [ ] table of contents option
- [x] Help/About page
- [ ] Interface to Mendeley?
- [ ] Python/_R_ interfcace (knitr/_Rmd_/ipython notebook)?
- [ ] Replace Python/_Flask_ with node.js?
